# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddcfdee0e68aaafd41c04d2e90777631dd8159f9810e3ea5a4c550adc2e9f12acce9836e942814bab3f190c80db307755e289f8646f71ba229ecff3ada4418b2

test:
  secret_key_base: f52ec58ca91b7c1fe5663bcc65ee3563cdc91ff19701747f61570ca84ded0af235be2bdbe75727bf26b9e236af22631c627ef5bacb5a9f719f0c184464bbf825

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
